name: LOC Report

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'docs/loc-*-badge.json'   # 避免因徽章文件更新被再次触发

concurrency:
  group: loc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloc:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # 需要回推 docs/loc-*-badge.json
    env:
      EXCLUDE_DIRS: node_modules,venv,.venv,build,dist,__pycache__
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc jq

      - name: Count LOC (json & markdown)
        run: |
          cloc --vcs=git --json --out=cloc.json --exclude-dir=${EXCLUDE_DIRS}
          cloc --vcs=git --md   --out=cloc.md   --exclude-dir=${EXCLUDE_DIRS}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: cloc-report
          path: |
            cloc.json
            cloc.md

      - name: Post summary
        run: |
          echo "## Lines of Code (cloc)" >> $GITHUB_STEP_SUMMARY
          cat cloc.md >> $GITHUB_STEP_SUMMARY

      - name: Build badges JSON
        run: |
          TOTAL_CODE=$(jq -r '.SUM.code // 0' cloc.json)
          TOTAL_ALL=$(jq -r '(.SUM.code // 0) + (.SUM.comment // 0) + (.SUM.blank // 0)' cloc.json)
          mkdir -p docs
          printf '{"schemaVersion":1,"label":"LOC(code)","message":"%s","color":"blue"}\n' "$TOTAL_CODE" > docs/loc-code-badge.json
          printf '{"schemaVersion":1,"label":"Lines(total)","message":"%s","color":"informational"}\n' "$TOTAL_ALL" > docs/loc-total-badge.json

      - name: Commit badge JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update LOC badges"
          file_pattern: docs/loc-*-badge.json
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

